### ISSUE TITLE
你就不能写点有用的东西么

### ISSUE THREAD

**Issue by KawaiiZapic** [KunoSayo/KunoSayo#1]
放个空仓库在这里浪费资源.

**Comment by KunoSayo** [comment]
I added useful  '东西' to 回忆 md语法
Thanks for your 建议

**Comment by KawaiiZapic** [comment]
![CA%C~~ 3_ECG7CG8R}0(Z97](https://user-images.githubusercontent.com/45936772/103631827-73ab1e80-4f7e-11eb-817b-6740e51542be.jpg)

**Comment by KunoSayo** [comment]
看不见图片 下一个！

**Comment by Au-Auraro** [comment]
YYS，You English is 本当上手。
